### ISSUE TITLE
[Enhancement] AAC Passthrough

### ISSUE THREAD

**Issue by sinnx3** [b-fuze/batch-encoder#8]
Default to AAC Passthrough if source audio is AAC to speed up encoding.
Fallback to encode AAC if source audio is anything else.

**Comment by b-fuze** [comment]
Ah, so detect if the audio is AAC and simply copy the stream. Sounds good. We can do that.

**Comment by sinnx3** [comment]
Edit script to allow 2-pass encoding configuration (either I'm really dumb, or it doesn't work probably both)
https://trac.ffmpeg.org/wiki/Encode/H.264#twopass
